### ISSUE TITLE
Add "identifier" checking

### ISSUE THREAD

**Issue by mrueschman** [nsrr/spout#101]
As part of dataset preparation/redaction, add ability for Spout to scour through a dataset and look for potentially identifiable data, e.g.:

- Dates (00/00/0000, 0000-00-00)
- Honorifics (e.g. "Dr.", "Mrs.", "Mr.", "Ms.")
- SSN (000-00-0000)
- Phone (000-000-0000)
- Zip code (00000)
- etc.

**Comment by remomueller** [comment]
We may be able to have some defaults, or also be able to customize this as well using some formats. Phone's could also potentially be in `000.000.0000` format, or `(000) 000-0000`. We may also want to consider that you could also say Mr Bob (without the period), in which case you may want to search for `mr ` (case insensitive)
