### ISSUE TITLE
Build a SAS script that will nicely format a dataset with the contents of the data dictionary

### ISSUE THREAD

**Issue by mrueschman** [nsrr/spout#55]
Much like has been done in Slice, build a .SAS file that would allow someone to easily import a CSV dataset into SAS and apply all the proper formats and labels and are pulled from the variables/domains.

**Comment by remomueller** [comment]
Additional note, these SAS scripts should be published when the dataset is deployed.

**Comment by remomueller** [comment]
@mrueschman: Potentially also do an R script as well?

**Comment by remomueller** [comment]
Removing from current milestone, as there are fairly major changes included already. This will be included in a future release.
