### ISSUE TITLE
Have 'spout c' output list of columns that appear entirely empty (for removal)

### ISSUE THREAD

**Issue by mrueschman** [nsrr/spout#80]
We have encountered variables that contain no data in various datasets, and our typical action is to remove these columns from datasets / data dictionaries.

This would sort of seem to be the opposite of #20, i.e. these are columns in a dataset with valid headers/variable names, yet all values in the dataset are nil / empty.

**Comment by remomueller** [comment]
Agreed, adding to next release milestone.

**Comment by remomueller** [comment]
Removing from 0.11.0 for the time being as this is a larger change, and we're closing in on a RC for 0.11.0. Will get back to this!
